### ISSUE TITLE
Search API for the cities or countries

### ISSUE THREAD

**Issue by kamalakil** [aainn/Ibn-Battuta#1]
We have to search for the API  and (optimal) find an API that provides us with countries names as well as their capitols with the related coordinates

**Comment by chadian** [comment]
I am having a bit of a trouble finding a high-quality API for both cities and countries. Since country and city data are two separate data points, it might make sense to try and find one API that does one of these very well, and then create a separate ticket for the other.

For example if we think cities are more interesting we start with a city API and come back and add a country data as a feature after.

Which one do we want to focus on first for our data? Cities or countries?

**Comment by PapaBravo** [comment]
The World Bank API gives us a list of countries with capitols.
[Example Query](http://api.worldbank.org/v2/countries?format=json)
[Dokumentation](https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information)

**Comment by PapaBravo** [comment]
restcountries.eu seems to give us all countries with their capitals and flags.
[All countries](https://restcountries.eu/rest/v2/all)
[Berlin Info](https://restcountries.eu/rest/v2/capital/berlin)
[Dokumentation](restcountries.eu)

The precision of the geo data is horrible though

**Comment by PapaBravo** [comment]
I registered with geonames.org. They have a free tier (no idea how many requests).

[Example Query for 100 cities](http://api.geonames.org/searchJSON?q=&cities=cities1000&maxRows=100&username=redi_basicfrontend)
